version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t "repo.treescale.com/snahelou22/middleware:${TAG}" .
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              TAG=0.1.$CIRCLE_BUILD_NUM
              docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}" repo.treescale.com/snahelou22/middleware
              docker push "repo.treescale.com/snahelou22/middleware:${TAG}"
            fi
      - deploy:
          name: Deploy app to Kubernetes using Weave FLux 
          command: |
            git clone https://github.com/snahelou/demo-gitops.git
            cd demo-gitops/demo
            git config credential.helper 'cache --timeout=120'
            git config user.email "${GITHUB_EMAIL}"
            git config user.name "CircleCI"
            sed -i "s/image: repo.treescale.com\/snahelou22\/middleware:.*$/image: repo.treescale.com\/snahelou22\/middleware:0.1.${CIRCLE_BUILD_NUM}/g" middle-deployment.yaml
            git add .
            git commit -m "Update via CircleCI"
            git push -q "https://${GITHUB_PERSONAL_TOKEN}@github.com/snahelou/demo-gitops.git" "${CIRCLE_BRANCH}"

